---

- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: latest
    update_cache: yes
 
- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Disable the default site
  file:
    path: "{{ item }}"
    state: absent
  notify:
    - reload nginx
  with_items:
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-available/default"

- name: Copy site configuration 
  become: yes
  copy: 
    src : templates/default.conf
    dest: /etc/nginx/sites-available/site.conf

- name: Setup the app
  file: src=/etc/nginx/sites-available/site.conf
        dest=/etc/nginx/sites-enabled/site.conf
        state=link
  notify: restart nginx

