---
# TODO: Use supervisor instead of direct shell

- name: App
  become: yes
  apt:
    pkg:
      - python-apt
      - build-essential
      - curl
    state: present

- name: Copy app
  become: yes
  copy: 
    src : files
    dest: /var/www/

- name: Start app_one
  shell: nohup python /var/www/files/app_one.py >/dev/null 2>&1 &

- name: Start app_two
  shell: nohup python /var/www/files/app_two.py >/dev/null 2>&1 &